### ISSUE TITLE
doc var in robloxdoc command will throw Unknown error when it is not a valid URL

### ISSUE THREAD

**Issue by Pythonic-Rainbow** [RbxAPI/Docs-Bot#10]
```python
@bot.command()
async def robloxdocs(ctx, doc: str, version: str):
```

If `doc` is not valid, it will produce an invalid URL because the URL will be ``{doc}.roblox.com``. Imagine if we put `abc` in `doc`, it will be ``abc.roblox.com``. When the `robloxdocs` command requests the URL, `request` lib will throw HTTP 403 error, `discord.py` catches it and processes in ``on_command_error``, which is set to send ``Unknown error occurred`` by our code.

Adding a catch in ``on_command_error`` that sends ``Wrong URL, no such roblox docs link`` might be enough?

**Comment by sbhadr** [comment]
I meant to do this a while ago and it’s my mistake as to why it hasn’t been corrected. I think that pushing error messages to DMs would be/is better than displaying them in the channel where the command is invoked. I’ve noticed a substantial amount of clutter.

**Comment by iranathan** [comment]
if you put it in that then if there is an other request error it would not make sence.

**Comment by Pythonic-Rainbow** [comment]
@iranathan then we use nested catch

**Comment by Pythonic-Rainbow** [comment]
Or <@427040024513609729> so that it will tag you in <#486715996791373836>

**Comment by sbhadr** [comment]
Wouldn’t it make more sense not to clutter the channel?

**Comment by iranathan** [comment]
how else would the user know the bot could not find the docs?
@Sanjay-B

**Comment by sbhadr** [comment]
Send them the message via DMs if it errors.
