### ISSUE TITLE
Automatically Load from Git

### ISSUE THREAD

**Issue by sbhadr** [RbxAPI/Docs-Bot#12]
I propose that we develop a system that allows you to automatically refresh the bot from git rather than updating the source repeatedly.

**Comment by iranathan** [comment]
Would you have to restart the bot or would you just check for a new push every now and then?

**Comment by iranathan** [comment]
We could do something like this. 

```PY
import requests
files = ['main.py']

for name in files:
    url = f'https://raw.githubusercontent.com/RbxAPI/Docs-Bot/rewrite/{name}'
    r = requests.get(url)
    with open(name, 'w') as code:
        code.write(r.text)
```
Maybe using a discord.py cog and referencing the file just created from the source code. We would have to change a lot of the code though. I really want to hear better ways to do this.

**Comment by sbhadr** [comment]
That would only work if ``main.py`` was hardcoded. You can load git files through raw but I’m not sure if you can do it as-is or if you have to create a file and explicitly write to it. 

Despite this, it may be worth refactoring ``main.py`` to not be touched. Load each command as cog and then, cache it via raw.

**Comment by sbhadr** [comment]
Even then, idk how you’d be able to detect a commit.

**Comment by Pythonic-Rainbow** [comment]
A git lib like [GitPython](https://gitpython.readthedocs.io/en/stable/)

**Comment by sbhadr** [comment]
Yeah, but how would you sync changes in real time?

**Comment by Pythonic-Rainbow** [comment]
Idk, maybe something like [PyUpdater](https://www.pyupdater.org/)

**Comment by sbhadr** [comment]
Looking into a solution for this tomorrow.

**Comment by sbhadr** [comment]
I'll go ahead and close this. The API list loads directly from git.
