### ISSUE TITLE
Embed limit with robloxdocs

### ISSUE THREAD

**Issue by iranathan** [RbxAPI/Docs-Bot#13]
When using the command `?robloxdocs` the embed can be over the max limit. 

This is by the docs `groups.roblox.com v1`, `api.roblox.com v1 & v2` (there are most likely more)

Any suggestion?

**Comment by sbhadr** [comment]
Page indexing. Check the limit and create “pages” via embeds.

**Comment by Pythonic-Rainbow** [comment]
Whats the limit tho

**Comment by sbhadr** [comment]
Realistically, 2048 characters. However, it’s 6000 is the max. https://discordapp.com/developers/docs/resources/channel#embed-limits

**Comment by sbhadr** [comment]
@iranathan You can fix this by taking reactions as page indexes or scrolling.

**Comment by iranathan** [comment]
Fixed #16
