### ISSUE TITLE
Discussion - Verify.py

### ISSUE THREAD

**Issue by sbhadr** [RbxAPI/Docs-Bot#20]
How do we feel about this file / concept? https://github.com/RbxAPI/Docs-Bot/blob/rewrite/verify.py

**Comment by iranathan** [comment]
It could use some fixing. instead of using requests like main.py its using `aiohttp`.
Also I believe you can't make a `ClientSession` (see line 8) outside of an asynchronous function in aiohttp, Otherwise I think its ok.

**Comment by sbhadr** [comment]
It might be better to move this functionality to a cog-like system and then, add a system where ``generate.py`` auto-generates cogs from the base repo.

**Comment by Pythonic-Rainbow** [comment]
Maybe extract common code from `verify()` and `on_member_join()`  
as well as using more straight-forward context variables e.g. ``ctx.author`` instead of ``ctx.message.author``, but that's really personal preference

**Comment by sbhadr** [comment]
Perhaps, if we moved ``verify.py`` as a cog and housed it in a ``cogs`` or the ``utils`` folder, that could work. The main issue is loading these cogs and determining changes to sync without doing some sort of ``git pull``. Perhaps, ``generate.py`` could be expanded to load modules independently. Just a thought.

**Comment by Pythonic-Rainbow** [comment]
btw @iranathan you can, but `aiohttp` doesn't like it.

**Comment by sbhadr** [comment]
Has been implemented ( https://github.com/RbxAPI/Docs-Bot/blob/rewrite/cogs/verification.py ). Closing.
