### ISSUE TITLE
Line Spacing bug via Main.py after it's been generated

### ISSUE THREAD

**Issue by sbhadr** [RbxAPI/Docs-Bot#21]
Recently started paying attention to the output file via ``generate.py`` and I noticed this weird line spacing bug. While it doesn't have any effect on the way it's executed, it's not visually sound. 

I'm able to reproduce this bug on Python Version ``3.7.2`` and ``3.7.4`` running a windows machine. However, on Mac, this bug seems to be non-existent.

**Comment by Pythonic-Rainbow** [comment]
Can you give an example of what you encountered ?
Sounds like a character encode incompatibility like CRLF on Windows vs LF on Unix

**Comment by sbhadr** [comment]
Here's a sample:
```python
# Windows
@bot event

async def on_ready():
     
    print(f"Logged in as {bot.user.name}, id: {bot.user.id}")
     
    print("--")
```
```python
# Mac
@bot event
async def on_ready():
    print(f"Logged in as {bot.user.name}, id: {bot.user.id}")
    print("--")
```
As labeled, the mac build seems to drop the empty space and formats correctly whereas the Windows build adds an extra space per every line. This is most-definitely an encoding issue on both conflicting devices.

**Comment by Pythonic-Rainbow** [comment]
Yep, this is a CRLF vs LF issue

**Comment by sbhadr** [comment]
Interesting, perhaps the way that the file is generated should be based on the ``Operating System``.

**Comment by sbhadr** [comment]
This commit pushes a fix to this bug. https://github.com/RbxAPI/Docs-Bot/commit/a20106887ed356f97d2f89dc319d07f72269c4de

**Comment by Pythonic-Rainbow** [comment]
However, Python should figure it out automatically when it writes to a file. Although the issue fixes, it doesn't really solve the cause 🤔

**Comment by sbhadr** [comment]
There are three places where I think this issue happens. 
1). If you write a python file on a Unix System and upload it to Github through git, perhaps the encoding is still Unix and never automatically changes to the base OS that the code is actually running on. 
2). ``file.write()`` doesn't automatically format like we think. 
3). ``Binary Strings`` & ``Raw Strings`` are incompatible between the two OS's.
