### ISSUE TITLE
Improves async efficiency

### ISSUE THREAD

**Issue by Pythonic-Rainbow** [RbxAPI/Docs-Bot#24]
Some IO functions can use async to reduce bot process time.  

Maybe in the future we should create a seperate thread that fetches files (e.g. `api_list.json`) in a timed matter so we don't need to proactively query the file every single time. This idea, however, means that it is possible the target wasn't updated when a user executes the command.

**Comment by sbhadr** [comment]
Which methods in particular?

**Comment by iranathan** [comment]
Stuff like `check_doc_exists` is using requests

**Comment by sbhadr** [comment]
I'm going to go ahead and close this since https://github.com/RbxAPI/Docs-Bot/pull/26 has been merged. Feel free to reopen if needed.
