### ISSUE TITLE
Update Legacy to be Synced with Rewrite

### ISSUE THREAD

**Issue by sbhadr** [RbxAPI/Docs-Bot#27]
How do we feel about possibly updating "Legacy" to be in line with "Rewrite"? 
(Written in Python) https://github.com/RbxAPI/Docs-Bot/tree/rewrite
(Written in JS) https://github.com/RbxAPI/Docs-Bot/tree/legacy

**Comment by Pythonic-Rainbow** [comment]
But why?

**Comment by sbhadr** [comment]
Server is going through a js rave.

**Comment by Pythonic-Rainbow** [comment]
We've done so much in Python we rewrote the entire bot. Imo absolutely no reason to port it to JS.

**Comment by sbhadr** [comment]
I feel like if we ported it to JS... Some neat features might come out of it. That in itself would be worth it.

**Comment by iranathan** [comment]
we would have way more contributes because so many people love nodejs

**Comment by Pythonic-Rainbow** [comment]
Actually I remember there was a reason for us to change to discord.py 🤔

**Comment by sbhadr** [comment]
I'm not saying switch to JS. All I'm suggesting is that converting our Python code to JS for legacy would benefit a lot of people. The bot would still be written/ran in/using Python.

**Comment by Pythonic-Rainbow** [comment]
How does it benefit others? We will continue using Python anyways

**Comment by sbhadr** [comment]
Others as in the overwhelming population in the server who use JS.

**Comment by Pythonic-Rainbow** [comment]
I am not changing my initial thought - the bot is designed in Python. If people want to contribute to the bot, then follow this project's nature because it is designed to use Python.

**Comment by sbhadr** [comment]
I agree. Closing.
